version: '3.7'

services:
  configurator:
    image: frappe/erpnext:${VERSION:?No image version set}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    command: >
      bench new-site {add your site name  as like this inhouse.clinic360.io}
      --no-mariadb-socket
      --db-root-password=${DB_PASSWORD}
      --admin-password=${ADMIN_PASSWORD}
    deploy:
      restart_policy:
        condition: none
    networks:
      - mariadb-network
      - bench-network

volumes:
  sites:
    external: true
    # set to name of the sites volume
    name: ${BENCH_NAME:-erpnext}_sites

networks:
  bench-network:
    name: ${BENCH_NAME:-erpnext}
    external: true
  mariadb-network:
    name: mariadb-network
    external: true
